version: '3.8'

services:
  postgres:
    container_name: postgres_kuber
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./deployments/postgres/schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"

  kuberrest:
    build: .
    container_name: kuberrest
    hostname: kuberrest
    image: kuberrest
    environment:
      - PG_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_DB:-postgres}:5432/${POSTGRES_DB:-postgres}
      - PORT=${HTTP_PORT:-8080}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg-data: